rebootourschools/technologytracker/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('technologytracker.views',
    url(r'^home/$', 'home'),
    url(r'^districtReporting/$', 'districtReporting'),
    url(r'^addDistrict/$', 'addDistrict'),
    url(r'^addSchool/$', 'addSchool'),
    url(r'^schools/$', 'schools'),
)

rebootourschools/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from technologytracker.views import *
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^techtracker/', include('technologytracker.urls')),
    url(r'^techtrackerapi/', include('technologytrackerapi.urls')),
    
    (r'^$', splash),
    (r'^home/$', home),
    (r'^districtReporting/$', districtReporting),
    (r'^addDistrict/$', addDistrict),
    (r'^addSchool/$', addSchool),
    (r'^deleteSchool/(?P<school_pk>\d+)/$', deleteSchool),
    (r'^addComputer/$', addComputer),
    (r'^deleteComputer/(?P<computer_pk>\d+)/$', deleteComputer),
    (r'^schools/$', schools),
    (r'^schooljson/(?P<school_pk>\d+)/$', schooljson),
    (r'^computerjson/(?P<computer_pk>\d+)/$', computerjson),
    (r'^school/(?P<school_id>\d+)/$', schoolDetail),
    

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

rebootourschools/technologytracker/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

####
# Choices
####    

OS_CHOICES = (
    ('OSX', 'OS X'),
    ('LINUX', 'Linux'),
    ('WINDOWS', 'Windows'),
)

HD_SIZE_CHOICES = (
    ('60', '60 GB'),
    ('128', '128 GB'),
    ('250', '250 GB'),
)

RAM_SIZE_CHOICES = (
    ('1', '1 GB'),
    ('2', '2 GB'),
    ('4', '4 GB'),
    ('8', '8 GB'),
)

MONITOR_SIZE_CHOICES = (
    ('12', '12"'),
    ('13', '13"'),
    ('14', '14"'),
    ('15', '15"'),
    ('16', '16"'),
    ('17', '17"'),
    ('18', '18"'),
    ('19', '19"'),
    ('20', '20"'),
    ('21', '21"'),
    ('22', '22"'),
    ('23', '23"'),
    ('24', '24"'),
)



####
# District and School related field
####

class District(models.Model):
    full_name = models.CharField(max_length=60)
    district_code = models.CharField(max_length=10)
    state = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    county = models.CharField(max_length=30)
    
    def __unicode__(self):
        return self.district_code        
        

class School(models.Model):

    SCHOOL_TYPE_CHOICES = (
        (1, 'Elementary School'),
        (2, 'Junior High School'),
        (3, 'High School'),
    )

    district = models.ForeignKey(District)
    full_name = models.CharField(max_length=60)
    school_code = models.CharField(max_length=10, null=True)
    school_type = models.SmallIntegerField(choices=SCHOOL_TYPE_CHOICES)
    student_count = models.PositiveIntegerField(null=True)
    teacher_count = models.PositiveIntegerField(null=True)

    def __unicode__(self):
        return self.full_name 
        
    def computer_count(self):
        return u"%s" % ("num computers")	
    computer_count.short_description = "Computers at this school"           

    class Meta:
        ordering = ['school_type']


class SchoolRoom(models.Model):

    SCHOOL_ROOM_TYPE_CHOICES = (
        (1, 'Class Room'),
        (2, 'Lab'),
    )

    CONNECTION_TYPE_CHOICES = (
        (1, 'Wired'),
        (2, 'Wireless'),
        (3, 'Mixed'),
    )

    room_name = models.CharField(max_length=60)
    room_description = models.TextField()
    room_connection_speed = models.IntegerField(null=True)
    room_connection_count = models.SmallIntegerField(null=True)
    room_connection_type = models.SmallIntegerField(choices=CONNECTION_TYPE_CHOICES,null=True)
    school_room_type = models.SmallIntegerField(choices=SCHOOL_ROOM_TYPE_CHOICES)



####
# User models
####

class TechTrackerAdminProfile(models.Model):
    """Super User for global reporting and account creation."""

    # Link to Django user model
    user = models.OneToOneField(User)

class DistrictUserProfile(models.Model):
    """District User for each district account."""

    # Link to Django user model
    user = models.OneToOneField(User)

    district = models.ForeignKey(District)

    def __unicode__(self):
        return u"%s/%s" % (self.user.username, self.district.full_name)


####
# Device models
####


class DistrictAsset(models.Model):
    district = models.ForeignKey(District)
    school = models.ForeignKey(School, null=True)
    room = models.ForeignKey(SchoolRoom, null=True)

class Computer(DistrictAsset):
    os = models.CharField(max_length=30, choices=OS_CHOICES, null=True)
    processor = models.CharField(max_length=30, null=True)
    hd_size = models.CharField(max_length=10, choices=HD_SIZE_CHOICES, null=True)
    ram = models.CharField(max_length=30, choices=RAM_SIZE_CHOICES, null=True)
    monitor_size = models.CharField(max_length=30, choices=MONITOR_SIZE_CHOICES, null=True)
    
    class Meta:
        ordering = ('school',)
        
    def __unicode__(self):
        return u"%s %s %s %s" % (self.os, self.processor, self.ram, self.hd_size)

rebootourschools/technologytracker/views.py
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext
from django.shortcuts import render_to_response
from GChartWrapper import *
from django.utils import simplejson
from collections import defaultdict
import ratioCalculator as ratios

from technologytracker.models import *
# Create your views here.

def splash(request):
    return render_to_response('splash.html')


@login_required(login_url='/login/')
def home(request):
    
    try:
        ###retrieve the district that the current user is assigned to
        districtUserProfile = DistrictUserProfile.objects.filter(user=request.user)
        userDistrict = District.objects.get(pk=districtUserProfile)
        
        ###retrieve all of the schools and computers in the user's district
        schools = School.objects.filter(district=userDistrict)
        schoolCount = len(schools)        
        computers = Computer.objects.filter(district=userDistrict)
        computerCount = len(computers)       
        
        ###compute counts for pill displays
        teacherCount = sum(school.teacher_count or 0 for school in schools)
        elementarySchoolCount = len([school for school in schools if school.school_type == 1])
        middleSchoolCount = len([school for school in schools if school.school_type == 2])
        highSchoolCount = len([school for school in schools if school.school_type == 3])
        
        schoolTypeChart = Pie3D([elementarySchoolCount,middleSchoolCount, highSchoolCount], encoding='text')
        schoolTypeChart.size(500,150)
        schoolTypeChart.color('4d89f9') 
        schoolTypeChart.label('Elementary Schools', 'Middle Schools', 'High Schools')        
        
        #compute ratios for schools, computer, and teachers
        studentsPerComputerRatioList, teachersPerComputerRatioList, computersPerSchoolCountList = ratios.computeDistrictRatios(schools, computers)

        studentsPerComputerDataset = [school[1] for school in studentsPerComputerRatioList]
        studentsPerComputerLabels = [school[0].full_name for school in studentsPerComputerRatioList]

        
        studentsPerComputerChart = VerticalBarStack(studentsPerComputerDataset) if studentsPerComputerDataset else ''
        if studentsPerComputerDataset:
          studentsPerComputerChart.color('0074CC')
          studentsPerComputerChart.bar(50,15)
          studentsPerComputerChart.marker('N*','black',0,-1,15)   
            
        
        return render_to_response('home.html',
                                  {'userDistrict': userDistrict, 
                                  'schools': schools, 
                                  'schoolCount':schoolCount,
                                  'computerCount': computerCount,
                                  'teacherCount': teacherCount,
                                  'elementarySchoolCount': elementarySchoolCount,
                                  'middleSchoolCount': middleSchoolCount,
                                  'highSchoolCount': highSchoolCount,
                                  'studentsPerComputerRatioList': studentsPerComputerRatioList,
                                  'teachersPerComputerRatioList': teachersPerComputerRatioList,
                                  'computersPerSchoolCountList': computersPerSchoolCountList,
                                  'studentsPerComputerChart': studentsPerComputerChart,
                                  'schoolTypeChart': schoolTypeChart
                                  },
                                  context_instance=RequestContext(request))
    
    ###exceptions
    except DistrictUserProfile.DoesNotExist:
        return HttpResponseNotFound('District profile not found')
    except District.DoesNotExist:
        return HttpResponseNotFound('District not found')


@login_required(login_url='/login/')    
def schoolDetail(request, school_id):
     
     try:
         ###retrieve the district that the current user is assigned to
         districtUserProfile = DistrictUserProfile.objects.filter(user=request.user)
         userDistrict = District.objects.get(pk=districtUserProfile)

         school = School.objects.get(pk=school_id, district=userDistrict)
         computers = Computer.objects.filter(school=school).order_by('os', 'ram')
         computerCount = len(computers)         
         
         osxCount = 0
         linuxCount = 0
         windowsCount = 0
         for computer in computers:
             if computer.os == 'OSX':
                 osxCount += 1
             elif computer.os == 'LINUX':
                 linuxCount += 1
             elif computer.os == 'WINDOWS':
                 windowsCount +=1
         osChart = ratios.generateOsPieChart(osxCount, linuxCount, windowsCount) if computers else ''
         
         ##hd chart
         smallHd = Computer.objects.filter(school=school, hd_size='60').count()
         mediumHd = Computer.objects.filter(school=school, hd_size='128').count()
         largeHd = Computer.objects.filter(school=school, hd_size='250').count()

         hdDataset = [smallHd, mediumHd, largeHd]
         hdChart = Pie3D( hdDataset )
         hdChart.label('60 GB','128 GB','250GB')
         hdChart.color('4d89f9','c6d9fd')
         hdChart.size(300,100)
         
         ##ram chart
         oneGb = Computer.objects.filter(school=school, ram='1').count()
         twoGb = Computer.objects.filter(school=school, ram='2').count()
         fourGb = Computer.objects.filter(school=school, ram='4').count()
         eightGb = Computer.objects.filter(school=school, ram='8').count() 

         ramDataset = [oneGb, twoGb, fourGb, eightGb]
         ramChart = Pie3D( ramDataset )
         ramChart.label('1 GB','2 GB','4 GB', '8 GB')
         ramChart.color('4d89f9','c6d9fd')
         ramChart.size(300,100)
 
         return render_to_response('schoolDetail.html',
                                   {'school':school,
                                    'computers':computers,
                                    'computerCount':computerCount,
                                    'osxCount':osxCount,
                                    'linuxCount':linuxCount,
                                    'windowsCount':windowsCount,
                                    'hdChoices':HD_SIZE_CHOICES,
                                    'ramChoices':RAM_SIZE_CHOICES,
                                    'osChart':osChart,
                                    'hdChart':hdChart,
                                    'ramChart':ramChart,
                                    'osChoices':OS_CHOICES, },
                                    context_instance=RequestContext(request))
 
     except School.DoesNotExist:        
         return HttpResponseNotFound('School not found')


@login_required(login_url='/login/')    
def schooljson(request, school_pk):

    try:

        ###retrieve the district that the current user is assigned to
        districtUserProfile = DistrictUserProfile.objects.filter(user=request.user)
        userDistrict = District.objects.get(pk=districtUserProfile)

        school = School.objects.get(pk=school_pk, district=userDistrict)

        data = { 'school_name': school.full_name,
                 'school_code': school.school_code,
                 'school_type': school.school_type,
                 'school_students': school.student_count,
                 'school_teachers': school.teacher_count,
                 'school_pk': school.pk, }

        return HttpResponse(simplejson.dumps(data), content_type='application/json')

    except School.DoesNotExist:

        return HttpResponseNotFound('School not found')


@login_required(login_url='/login/')    
def computerjson(request, computer_pk):

    try:

        ###retrieve the district that the current user is assigned to
        districtUserProfile = DistrictUserProfile.objects.filter(user=request.user)
        userDistrict = District.objects.get(pk=districtUserProfile)

        computer = Computer.objects.get(pk=computer_pk, district=userDistrict)

        data = { 'computer_school': computer.school.pk,
                 'computer_pk': computer.pk,
                 'computer_hd_size': computer.hd_size,
                 'computer_monitor_size': computer.monitor_size,
                 'computer_processor': computer.processor,
                 'computer_ram': computer.ram,
                 'computer_os': computer.os, }

        return HttpResponse(simplejson.dumps(data), content_type='application/json')

    except School.DoesNotExist:

        return HttpResponseNotFound('Computer not found')


@login_required(login_url='/login/')
def districtReporting(request):
    districtUserProfile = DistrictUserProfile.objects.filter(user=request.user)
    userDistrict = District.objects.get(pk=districtUserProfile)
    districtAssets = userDistrict.districtasset_set

    ###retrieve all of the schools in the user's district
    schools = School.objects.filter(district=userDistrict)
    schoolCount = School.objects.filter(district=userDistrict).count()
    
    schoolDataset = []
    schoolLabels = []
    computerCountChart = ''
    for school in schools:
        schoolLabels.append(school.full_name)
        computerCount = Computer.objects.filter(school=school).count()
        schoolDataset.append(computerCount)

        computerCountChart = VerticalBarStack(schoolDataset)
        computerCountChart.color('4d89f9','c6d9fd')
        computerCountChart.title('Count by school')
        computerCountChart.size(600,375)
        
    horizontalBarStack = HorizontalBarStack(['hello','world'], encoding='simple')
    horizontalBarStack.color('4d89f9','c6d9fd')
    horizontalBarStack.title('Memory')
    horizontalBarStack.size(400,250)    
    horizontalBarStack.label('1 GB','2 GB','4 GB', '8 GB')
    

rebootourschools/technologytracker/templates/addDistrict.html
{% extends "base.html" %}

{% block content %}
<h2>Add a new District:</h2>
<br /><br />
<form action="/addDistrict/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

rebootourschools/technologytracker/templates/addSchool.html
{% extends "base.html" %}

{% block content %}
<h2>Add a new School:</h2>
<br /><br />
<form action="/addSchool/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

rebootourschools/technologytracker/templates/districtReporting.html
{% extends "base.html" %}


{% block content %}

<h1>{% block title %}{{ userDistrict.full_name }} ({{ userDistrict.district_code }}){% endblock %}</h1>
<h3>{{ userDistrict.city }}, {{ userDistrict.state }}</h3><br/>
<h4>{{ schoolCount }} schools in this district
<hr/>

<div>
<img src="{{ horizontalBarStack }}">


<img src="{{ verticalBarGroup }}">

<img src="{{ meter }}">

<img src="{{ verticalBarStack }}">
</div>

{% endblock %}

rebootourschools/technologytracker/templates/districts.html
{% extends "base.html" %}

{% block content %}
<h2>Districts:</h2>
{% for district in districts %}
  <li>
    <a href="/districtDetail/">{{ district.full_name }}</a>
  </li>
{% endfor %}
{% endblock %}

rebootourschools/technologytracker/templates/schoolDetail.html
{% extends "base.html" %}


{% block content %}

<h2>{{ school }}</h2>
<div class="tabbable">

  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#reporting" data-toggle="tab">Reporting</a>
    </li>    
	<li>
      <a href="#rooms" data-toggle="tab">Rooms</a>
    </li>
    <li>
      <a href="#computers" data-toggle="tab">Computers</a>
    </li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane active" id="reporting">
		<div id="stats">
			<div class="row">
				<div class="span4 stat">
					<h4 class="statTitle">Number of Computers</h4>
					<p class="statValue">{{ computerCount }}</p>
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Number of Teachers</h4>
					<p class="statValue">{{ school.teacher_count }}</p>
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Number of Students</h4>
					<p class="statValue">{{ school.student_count }}</p>
				</div>
			</div>
		</div>
		
		<div id="stats">
			<div class="row">
				<div class="span4 stat">
					<h4 class="statTitle">Operating Systems</h4>
					<img src="{{ osChart }}">
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Memory (Hard Drives)</h4>
					<img src="{{ hdChart}}">
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Memory (RAM)</h4>
					<img src="{{ ramChart }}">
				</div>
			</div>
		</div>

		<div id="stats">
			<div class="row">
				<div class="span4 stat c">
					<h4 class="statTitle">Worst Students-per-Computer Ratios</h4>
				</div>
				<div class="span8 stat">
					<h4 class="statTitle">School Types</h4>
				</div>
			</div>
		</div>

		<div id="stats">
			<div class="row">
				<div class="span4 stat">
					<h4 class="statTitle">Worst Students-per-Computer Ratios</h4>
					<ul>
					{% for ratio in studentsPerComputerRatioList %}
						<li><a href="/school/{{ ratio.0.id }} ">{{ ratio.0.full_name }}</a>:  {{ ratio.1 }}</li>
					{% endfor %}
					</ul>
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Least Number of Computers</h4>
					<ul>
					{% for ratio in computersPerSchoolCountList %}
						<li><a href="/school/{{ ratio.0.id }} ">{{ ratio.0.full_name }}</a>:  {{ ratio.1 }}</li>
					{% endfor %}
					</ul>
				</div>
				<div class="span4 stat">
					<h4 class="statTitle">Worst Teacher-per-Computer Ratios</h4>
					<ul>
					{% for ratio in teachersPerComputerRatioList %}
						<li><a href="/school/{{ ratio.0.id }} ">{{ ratio.0.full_name }}</a>:  {{ ratio.1 }}</li>
					{% endfor %}
					</ul>
				</div>
			</div>
		</div>
    </div>

    <div class="tab-pane" id="rooms">

       <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Room Type</th>
            <th>Room Number</th>
            <th>Network Connections</th>
            <th>Network Connection Type</th>
            <th>Network Speed</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for room in school_rooms %}
          <tr>
            <td>{{ room.get_school_room_type_display }}</td>
            <td>{{ room.room_name }}</td>
            <td>{{ room.room_connection_count }}</td>
            <td>{{ room.get_room_connection_type_display }}</td>
            <td>{{ room.room_connection_speed }}</td>
            <td>
              <a name="editRoom{{ room.pk }}" id="editRoom{{ room.pk }}" class="btn btn-info btn-mini" roomID="{{ room.pk }}" href="/updateRoom/{{ room.pk }}/">Edit</a>
              <a name="deleteRoom{{ room.pk }}" id="deleteRoom{{ room.pk }}" class="btn btn-danger btn-mini" href="/deleteRoom/{{ room.pk }}/">Delete</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <br/>
      <br/>

      <a name="addRoom" id="addRoom" class="btn-primary btn-large" href="/addRoom/">Add Room</a>

    </div>

    <div class="tab-pane" id="computers">

      <h3>Total Computers: {{ computerCount }}</h3>
      <h4>{{ osxCount }} Mac | {{ linuxCount }} Linux | {{ windowsCount }} Windows</h4>

      <br/>

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>OS</th>
            <th>Processor</th>
            <th>HD Size</th>
            <th>RAM</th>
            <th>Monitor Size</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for computer in computers %}
          <tr>
            <td>{{ computer.os }}</td>
            <td>{{ computer.processor }}</td>
            <td>{{ computer.hd_size }}</td>
            <td>{{ computer.ram }}</td>
            <td>{{ computer.monitor_size }}</td>
            <td>
              <a name="editComputer{{ computer.pk }}" id="editComputer{{ computer.pk }}" class="btn btn-info btn-mini"
                  computerID="{{ computer.pk }}" href="/updateComputer/{{ computer.pk }}/">Edit</a>
              <a name="deleteComputer{{ computer.pk }}" id="deleteComputer{{ computer.pk }}" class="btn btn-danger btn-mini" href="/deleteComputer/{{ computer.pk }}/">Delete</a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

      <br/>
      <br/>

      <a name="addComputer" id="addComputer" class="btn-primary btn-large" href="/addComputer/">Add Computers</a>
    </div>

  </div>
</div>

<div class="modal hide" id="addComputerModal">
  <div class="modal-header">
    <a href="#" class="close" id="closeModal" data-dismiss="modal">&times;</a>
    <h2>Add Computers:</h2>
  </div>
  <div class="modal-body">
    <form action="/addComputer/" id="addComputerForm" method="post">
      {% csrf_token %}
      <p>
        <label for="computerOS">OS:</label>
        <select name="computerOS" id="computerOS">
        {% for opt in osChoices %}
          <option value="{{ opt.0 }}">{{ opt.1 }}</option>
        {% endfor %}
        </select>
      </p>
      <p>
        <label for="computerProcessor">Processor:</label>
        <input type="text" name="computerProcessor" id="computerProcessor" />
      </p>
      <p>
        <label for="hdSize">HD Size:</label>
        <select name="hdSize" id="hdSize">
        {% for opt in hdChoices %}
          <option value="{{ opt.0 }}">{{ opt.1 }}</option>
        {% endfor %}
        </select>
      </p>
      <p>
        <label for="ram">RAM:</label>
        <select name="ram" id="ram">
        {% for opt in ramChoices %}
          <option value="{{ opt.0 }}">{{ opt.1 }}</option>
        {% endfor %}
        </select>
      </p>
      <p>
        <label for="numberOfComputers">Number of Computers:</label>
        <input type="text" name="numberOfComputers" id="numberOfComputers" />
      </p>
      <input type="hidden" name="schoolPk" id="schoolPk" value="{{ school.pk }}" />
      <input type="hidden" name="computerPk" id="computerPk" value="" />
    </form>
  </div>
  <div class="modal-footer">
    <input type="button" class="btn" id="closeButton" value="Cancel" />
    <input type="button" class="btn btn-primary" id="addButton" value="Save" />
  </div>
</div>


<script type="text/javascript">
  $(document).ready( function(){
        
    $('#closeButton').click(function() {
      $('#addComputerModal').modal('hide');
    });

    $('#addButton').click( function() {
      $('#addComputerForm').submit();
    });

    $('#addComputer').click( function(e) {
      e.preventDefault();
      $('#computerOS').val('');
      $('#computerProcessor').val('');
      $('#hdSize').val('');
      $('#ram').val('');
      $('#computerPk').val('');
      $('#numberOfComputers').parent().show();
      $('#addComputerModal').modal('show');
    });

    $('a[name^="editComputer"]').click( function(e) {
      e.preventDefault();
      $.ajax({
        url: '/computerjson/' + this.getAttribute('computerid') + '/'
      }).done( function(data) {
        $('#computerOS').val(data.computer_os);
        $('#computerProcessor').val(data.computer_processor);
        $('#hdSize').val(data.computer_hd_size);
        $('#ram').val(data.computer_ram);
        $('#schoolPk').val(data.computer_school);
        $('#computerPk').val(data.computer_pk);
        $('#numberOfComputers').parent().hide();
        $('#addComputerModal').modal('show');
      });
    });
  });
</script>


{% endblock %}

rebootourschools/technologytracker/templates/schools.html
{% extends "base.html" %}

{% block content %}
<h2>Schools:</h2>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>School Name</th>
      <th>School Type</th>
      <th>School City</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for school in schools %}
    <tr>
      <td><a href="/school/{{ school.pk }}/">{{ school.full_name }}</a></td>
      <td>{{ school.get_school_type_display }}</td>
      <td>{{ school.city }}</td>
      <td>
        <a name="editSchool{{ school.pk }}" id="editSchool{{ school.pk }}" class="btn btn-info btn-mini"
            schoolID="{{ school.pk }}" href="/updateSchool/{{ school.pk }}/">Edit</a>
        <a name="deleteSchool{{ school.pk }}" id="deleteSchool{{ school.pk }}" class="btn btn-danger btn-mini" href="/deleteSchool/{{ school.pk }}/">Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<br/>
<br/>

<a name="addSchool" id="addSchool" class="btn-primary btn-large" href="/addSchool/">Add School</a>

<div class="modal hide" id="addSchoolModal">
  <div class="modal-header">
    <a href="#" class="close" id="closeModal" data-dismiss="modal">&times;</a>
    <h2>Add a new School:</h2>
  </div>
  <div class="modal-body">
    <form action="/addSchool/" id="addSchoolForm" method="post">
      {% csrf_token %}
      <p>
        <label for="schoolName">Full Name:</label>
        <input type="text" name="schoolName" id="schoolName" />
      </p>
      <p>
        <label for="schoolCode">School Code:</label>
        <input type="text" name="schoolCode" id="schoolCode" />
      </p>
      <p>
        <label for="schooltype">School Type:</label>
        <select name="schoolType" id="schooltype">
        {% for id, label in schoolTypes %}
          <option value="{{ id }}">{{ label }}</option>
        {% endfor %}
        </select>
      </p>
      <p>
        <label for="schoolStudents">School Students:</label>
        <input type="text" name="schoolStudents" id="schoolStudents" />
      </p>
      <p>
        <label for="schoolTeachers">School Teachers:</label>
        <input type="text" name="schoolTeachers" id="schoolTeachers" />
      </p>
      <input type="hidden" name="schoolPk" id="schoolPk" value="" />
    </form>
  </div>
  <div class="modal-footer">
    <input type="button" class="btn" id="closeButton" value="Cancel" />
    <input type="button" class="btn btn-primary" id="addButton" value="Save" />
  </div>
</div>


<script type="text/javascript">
  $(document).ready( function(){
        
    $("#closeButton").click(function() {
      $('#addSchoolModal').modal('hide');
    });

    $("#addButton").click( function() {
      $("#addSchoolForm").submit();
    });

    $('#addSchool').click( function(e) {
      e.preventDefault();
      $('#schoolCode').val('');
      $('#schoolName').val('');
      $('#schoolPk').val('');
      $('#schoolStudents').val('');
      $('#schoolTeachers').val('');
      $('#addSchoolModal').modal('show');
    });

    $('a[name^="editSchool"]').click( function(e) {
      e.preventDefault();
      $.ajax({
        url: '/schooljson/' + this.getAttribute('schoolid') + '/'
      }).done( function(data) {
        $('#schoolCode').val(data.school_code);
        $('#schoolName').val(data.school_name);
        $('#schoolStudents').val(data.school_students);
        $('#schoolTeachers').val(data.school_teachers);
        $('#schoolPk').val(data.school_pk);
        $('#addSchoolModal').modal('show');
      });
    });

  });
</script>


{% endblock %}